# Generated by Django 2.2.2 on 2019-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randLang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_words',
            name='word',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_created',
            name='definition',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_created',
            name='user_word',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
