# Generated by Django 2.2.2 on 2019-07-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randLang', '0002_auto_20190726_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_created',
            name='language',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
