# Generated by Django 2.2.2 on 2019-07-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randLang', '0003_auto_20190726_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict_words',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_created',
            name='definition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_created',
            name='user_word',
            field=models.CharField(default='', max_length=100),
        ),
    ]
